### PR TITLE
Light/Dark themer added for Winform title bar

### PR DESCRIPTION
**Pull request by DubyaDude**
Dark theme ftw

### CODE REVIEW

**Comment by Myrkie** [comment]
gay

**Comment by DubyaDude** [comment]
> gay

u

**Comment by Myrkie** [comment]
> > gay
> 
> u

U

**Comment by DubyaDude** [comment]
> > > gay
> > 
> > 
> > u
> 
> U

diDie6y

**Comment by Myrkie** [comment]
nou

**Comment by DubyaDude** [comment]
> > > gay
> > 
> > 
> > u
> 
> U

[image]https://i.imgur.com/diDie6y.gif[/image]

> nou

No U

**Comment by Myrkie** [comment]
gayer

**Comment by DubyaDude** [comment]
> gayer

gayest

**Comment by Myrkie** [comment]
> > gayer
> 
> gayest

 gayerist

**Comment by DubyaDude** [comment]
> > > gayer
> > 
> > 
> > gayest
> 
> gayerist

gayeristd've

**Comment by Myrkie** [comment]
> > > > gayer
> > > 
> > > 
> > > gayest
> > 
> > 
> > gayerist
> 
> gayeristd've

gayergayiest that  could of gayed

**Comment by DubyaDude** [comment]
> > > > > gayer
> > > > 
> > > > 
> > > > gayest
> > > 
> > > 
> > > gayerist
> > 
> > 
> > gayeristd've
> 
> gayergayiest that could of gayed

gayest of all gay kind, sitting on the gay throne watching over the gay land of the gays. basking in the beauty of the gayness of society.

**Comment by Myrkie** [comment]
> > > > > > gayer
> > > > > 
> > > > > 
> > > > > gayest
> > > > 
> > > > 
> > > > gayerist
> > > 
> > > 
> > > gayeristd've
> > 
> > 
> > gayergayiest that could of gayed
> 
> gayest of all gay kind, sitting on the gay throne watching over the gay land of the gays. basking in the beauty of the gayness of society.

bruh

**Pull request merged**
